name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'Twrp_Device_Genter'
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://doc-0o-6k-docs.googleusercontent.com/docs/securesc/pimr9ki65gh4mqfvf3jqgf9b3jt6f2i4/j02mubrb0qhnttqj2mk3hik6n5317h6l/1666545825000/18086689018600112187/18086689018600112187/1Y46abItyp2q1H4V8_mQp9vQ70vr4g50G?e=download&ax=ALW9-sAGkpFPfBJzNr6wSKSsVU4wGho_3IB0N7r-np5YVMuZMtyDshChWiWO0KvO7lYUqu96m39-i-iG8GE81TntA6d596E7gS-_YR7tpA6j07anGuz4nF_MUU2wS8zvOPtts8kxhBTIRkMX_aLB7zFgGb04cUElOkxT70JuLzOw96tb6zdXcoELUONdt_5ZcSsHUS8r90MhNnbOi4xwVD0VpwS9KljxGzrj3aLXe8j6JW7fYPhM6gU1nMNwwZQVKsuqB1mXX6mapjfNGM3xtySFu0AQgia0DcM1zy24BLnt4VB7yC7yUa3F2DzKlTxL_srPlUA3j5mhesSSfF6mnWVHo5IDvx2Tu8vn-po_AHuZsEtWPpvPs-9pT3ZTR7cuD14hpvrSpGQkutKgk0EokAW9dFzfrOOe-u8M8E_-wdK5o7nDjnul9G-rVZLwv-t_LM1tdORY54X8Q13L9uMtS4JLff8xFCNK3x41RCAlvsORrPJPrYTM_lyZanyEoNHafCYn0OTDWAzrzMm3GEeLoK9qvX6HQs22HWwPLCHY_piW5D3iceTFc156UE4co1untCpmXsyZzlw9uhQCLZe-QXqn_cr7VN_1Vkm4b6Nfd_Tp_EM_5D9prNmJDVAhnZ5nZDp85EL6qgfLErr4wGaXgO8tQlhGIL3MJpjOk8qdG3bLL0l-iQET05y196pghp5rhp3Bhvdseh0RB7kyyfSHn8gJm2SX0S4UYRf1b_ZvtGWEs8a6ruJ3YnysRopBf_btbBbJUxGm3ryp4drlOWrW76cxXzfOrhyTi2WuxhQnQY9ybUPKH5TmhfAwzB0R7hxfUmXBGfBpKyHJGHTfIF80-Wm3xa9xrrAT_7nN3icWCDNnAjVh0BW_X7BceVexBCK5oz0ctg&uuid=2943b73e-6066-47a9-bb1c-168113cf6a53&authuser=0'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
      
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var
      
    - name: Install TWRP generator 
      run: |
        pip3 install twrpdtgen
        mkdir dt
    
    - name: Download boot or recovery img
      run: |
        wget ${{ github.event.inputs.IMG_URL }}
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
